/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Legacy knicks colors kept for backward compat
        knicks: {
          blue:   '#006BB6',
          orange: '#F58426',
          silver: '#BEC0C2',
          dark:   '#0A0A0A',
        },
        // New design system
        'inverse-surface': '#e5e2e1',
        'outline-variant': '#564336',
        'outline': '#a58c7d',
        'surface-container-highest': '#353534',
        'surface-tint': '#ffb786',
        'surface-container-lowest': '#0e0e0e',
        'on-secondary-container': '#dbe9ff',
        'secondary': '#a0caff',
        'tertiary-fixed-dim': '#4ae176',
        'surface-container-low': '#1c1b1b',
        'on-secondary-fixed': '#001c37',
        'on-error-container': '#ffdad6',
        'on-tertiary': '#003915',
        'on-tertiary-fixed-variant': '#005321',
        'surface': '#131313',
        'primary-fixed': '#ffdcc6',
        'background': '#131313',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-fixed': '#002109',
        'secondary-container': '#006bb6',
        'primary-container': '#f58426',
        'on-secondary': '#003259',
        'on-primary-container': '#5c2b00',
        'secondary-fixed-dim': '#a0caff',
        'on-primary-fixed-variant': '#723600',
        'surface-dim': '#131313',
        'on-primary-fixed': '#311300',
        'inverse-primary': '#964900',
        'surface-bright': '#3a3939',
        'tertiary-container': '#06bb55',
        'primary-fixed-dim': '#ffb786',
        'tertiary': '#4ae176',
        'on-surface-variant': '#ddc1b1',
        'on-primary': '#502400',
        'error-container': '#93000a',
        'on-error': '#690005',
        'secondary-fixed': '#d2e4ff',
        'primary': '#ffb786',
        'inverse-on-surface': '#313030',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
        'surface-container': '#201f1f',
        'error': '#ffb4ab',
        'tertiary-fixed': '#6bff8f',
        'on-tertiary-container': '#00431a',
        'on-surface': '#e5e2e1',
        'on-secondary-fixed-variant': '#00497e',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        // Legacy
        display: ['Bebas Neue', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}
