import { Link } from "react-router-dom"
import { Helmet } from "react-helmet-async"

const S = {
  bg: "#131313", surface: "#1c1b1b", surfaceHigh: "#2a2a2a",
  border: "rgba(255,255,255,0.08)", orange: "#F58426", peach: "#ffb786",
  text: "#e5e2e1", textMuted: "#ddc1b1",
}

export default function AboutPage() {
  return (
    <div style={{ background: S.bg, minHeight: "100vh" }}>
      <Helmet>
        <title>About KnicksHub | AI-Powered Knicks Betting Analysis</title>
        <meta name="description" content="KnicksHub is an AI-powered New York Knicks betting analysis platform built by a fan, for fans." />
      </Helmet>

      <div style={{ background: S.surface, borderBottom: `1px solid ${S.border}`, padding: "2rem 2.5rem" }}>
        <h1 style={{ fontFamily: "Space Grotesk, sans-serif", fontWeight: 900, fontSize: "clamp(2rem, 5vw, 3.5rem)", textTransform: "uppercase", letterSpacing: "-0.03em", color: S.text, margin: "0 0 0.5rem", fontStyle: "italic" }}>
          About <span style={{ color: S.peach }}>KnicksHub</span>
        </h1>
        <p style={{ color: S.textMuted, fontSize: "0.875rem", margin: 0 }}>The Courtside Editorial</p>
      </div>

      <div style={{ padding: "3rem 2.5rem", maxWidth: "800px" }}>
        <div style={{ display: "flex", flexDirection: "column", gap: "2rem" }}>
          {[
            ["What is KnicksHub?", "KnicksHub is an AI-powered New York Knicks betting analysis platform. We generate daily predictions, best bets, and player prop picks using real-time injury data, team stats, historical trends, and machine learning models — dropping articles ~45 minutes before tip-off on every game day."],
            ["Who makes this?", "KnicksHub is built and operated by Nick Knicks — a die-hard Knicks fan who combines a passion for the team with a data-driven approach to sports betting. Every article is generated by a custom AI trained on Knicks-specific betting patterns."],
            ["How do the picks work?", "Our AI analyzes spread, moneyline, and over/under lines using a composite scoring model that weighs offensive/defensive ratings, rest days, home/away splits, injury impact, and historical matchup data. Prop picks focus on Brunson, KAT, Bridges, and OG — the four core Knicks bettable players."],
            ["Responsible Gambling", "Sports betting should be entertainment only. Never bet more than you can afford to lose. If you need help: 1-800-522-4700 (National Problem Gambling Helpline) or 1-888-789-7777 (Connecticut). Must be 21+. KnicksHub is not affiliated with the NBA or the New York Knicks."],
          ].map(([title, body]) => (
            <div key={title as string} style={{ borderLeft: `3px solid ${S.orange}`, paddingLeft: "1.5rem" }}>
              <h2 style={{ fontFamily: "Space Grotesk, sans-serif", fontWeight: 900, fontSize: "1.125rem", textTransform: "uppercase", letterSpacing: "-0.01em", color: S.peach, marginBottom: "0.75rem" }}>{title}</h2>
              <p style={{ color: S.textMuted, lineHeight: 1.75, fontSize: "1rem", fontFamily: "Inter, sans-serif", margin: 0 }}>{body}</p>
            </div>
          ))}
        </div>

        <div style={{ display: "flex", gap: "1rem", marginTop: "2.5rem", flexWrap: "wrap" }}>
          {[["Privacy Policy", "/privacy"], ["Terms of Service", "/terms"], ["Predictions", "/predictions"]].map(([label, to]) => (
            <Link key={to} to={to} style={{ background: S.surface, color: S.textMuted, padding: "0.625rem 1.25rem", fontFamily: "Space Grotesk, sans-serif", fontWeight: 700, fontSize: "0.75rem", textTransform: "uppercase", letterSpacing: "0.1em", textDecoration: "none", transition: "color 0.15s" }}
              onMouseEnter={e => (e.currentTarget.style.color = S.peach)}
              onMouseLeave={e => (e.currentTarget.style.color = S.textMuted)}
            >{label}</Link>
          ))}
        </div>
      </div>
    </div>
  )
}
